version: '3.8'

services:
  frontend:
    image: deepanshuthree/frontend:latest  # Use image instead of build
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped  # Ensure frontend container restarts if it fails

  backend:
    image: deepanshuthree/backend:latest  # Use image instead of build
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    restart: unless-stopped  # Ensure backend container restarts if it fails

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped  # Ensure MongoDB container restarts if it fails

volumes:
  mongo-data:
    driver: local  # Define a local volume for MongoDB data storage
